# Generated by Django 2.0.7 on 2018-07-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180715_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female')], default='m', max_length=1),
        ),
    ]
