# Generated by Django 2.0.7 on 2018-07-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20180727_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False, max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
