# Generated by Django 2.0.7 on 2018-07-28 06:19

import article.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='main_image',
            field=models.ImageField(blank=True, upload_to=article.models.path_and_rename, verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='article.Comment', verbose_name='Родительский комментарий'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='gallery', verbose_name='Изображение'),
        ),
    ]
