# Generated by Django 2.0.7 on 2018-08-01 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20180731_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='gallery',
        ),
        migrations.AddField(
            model_name='image',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='article.Article', verbose_name='Статья'),
            preserve_default=False,
        ),
    ]
