# Generated by Django 2.0.7 on 2018-08-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20180803_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=60, unique=True, verbose_name='Заголовок'),
        ),
    ]
