# Generated by Django 2.0.7 on 2018-08-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsedarticle',
            name='title',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
